# Generated by Django 5.2.1 on 2025-05-26 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('awaiting', 'Ожидает'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], max_length=10, verbose_name='Статус предложения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('ad_receiver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='received_proposals', to='ads.ad', verbose_name='Отправитель')),
                ('ad_sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sent_proposals', to='ads.ad', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'db_table': 'exchange_proposal',
                'ordering': ['-created_at'],
            },
        ),
    ]
