# Generated by Django 5.2.1 on 2025-05-27 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeproposal',
            options={'verbose_name': 'Предложение обмена', 'verbose_name_plural': 'Предложения обмена'},
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to='ads.ad', verbose_name='Объявление получателя'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to='ads.ad', verbose_name='Объявление отправителя'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='exchangeproposal',
            constraint=models.UniqueConstraint(fields=('ad_sender', 'ad_receiver'), name='unique_proposal'),
        ),
        migrations.AlterModelTable(
            name='exchangeproposal',
            table=None,
        ),
    ]
